### ISSUE TITLE
Smoke detector support?

### ISSUE THREAD

**Issue by kevin-david** [XaF/qolsysgw#1]
Hello! Saw your post [over here](https://community.home-assistant.io/t/qolsys-iq-panel-2-and-3rd-party-integration/231405/452) and figured I'd share the one sensor I've found so far that's not working for me: my smoke detector "listening" device. Here's the errors from the debug log:

```
2022-01-01 00:17:54.210193 DEBUG qolsys_panel: Data received (len: 156): {"event":"ZONE_EVENT","zone_event_type":"ZONE_ACTIVE","version":1,"zone":{"status":"Closed","zone_id":7},"requestID":"46aaf2df-39cf-49f9-a814-e6a77a5eecd2"}
2022-01-01 00:17:54.215553 DEBUG qolsys_panel: Qolsys callback for event: <QolsysEventZoneEventActive zone=namespace(id=7, status='Closed') version=1>
2022-01-01 00:17:54.216788 DEBUG qolsys_panel: call_service: mqtt/publish, {'namespace': 'mqtt', 'topic': 'qolsys/qolsys_panel/event', 'payload': '{"event": "ZONE_EVENT", "zone_event_type": "ZONE_ACTIVE", "version": 1, "zone": {"status": "Closed", "zone_id": 7}, "requestID": "46aaf2df-39cf-49f9-a814-e6a77a5eecd2"}'}
2022-01-01 00:17:54.232691 DEBUG qolsys_panel: Received MQTT_MESSAGE with data={'topic': 'qolsys/qolsys_panel/event', 'wildcard': '#', 'payload': '{"event": "ZONE_EVENT", "zone_event_type": "ZONE_ACTIVE", "version": 1, "zone": {"status": "Closed", "zone_id": 7}, "requestID": "46aaf2df-39cf-49f9-a814-e6a77a5eecd2"}'} and kwargs={'topic': 'qolsys/qolsys_panel/event', '__thread_id': 'MainThread'}
2022-01-01 00:17:54.239479 DEBUG qolsys_panel: MQTT callback for event: <QolsysEventZoneEventActive zone=namespace(id=7, status='Closed') version=1>
2022-01-01 00:17:54.249167 DEBUG qolsys_panel: ACTIVE zone=namespace(id=7, status='Closed')
2022-01-01 00:18:13.824217 DEBUG qolsys_panel: Data received (len: 333): {"event":"ZONE_EVENT","zone_event_type":"ZONE_UPDATE","zone":{"id":"067B27","type":"SmokeDetector","name":"Basement Smoke Detector","group":"smoke_heat","status":"Closed","state":"0","zone_id":7,"zone_physical_type":9,"zone_alarm_type":9,"zone_type":5,"partition_id":0},"version":1,"requestID":"b2932809-6623-4752-8b77-57bc0313a99c"}
2022-01-01 00:18:13.829215 WARNING qolsys_panel: sensor of unknown type: {'id': '067B27', 'type': 'SmokeDetector', 'name': 'Basement Smoke Detector', 'group': 'smoke_heat', 'status': 'Closed', 'state': '0', 'zone_id': 7, 'zone_physical_type': 9, 'zone_alarm_type': 9, 'zone_type': 5, 'partition_id': 0}
2022-01-01 00:18:13.833073 DEBUG qolsys_panel: Qolsys callback for event: None
2022-01-01 00:18:13.837619 ERROR qolsys_panel: Error calling callback for event: {"event":"ZONE_EVENT","zone_event_type":"ZONE_UPDATE","zone":{"id":"067B27","type":"SmokeDetector","name":"Basement Smoke Detector","group":"smoke_heat","status":"Closed","state":"0","zone_id":7,"zone_physical_type":9,"zone_alarm_type":9,"zone_type":5,"partition_id":0},"version":1,"requestID":"b2932809-6623-4752-8b77-57bc0313a99c"}
Traceback (most recent call last):
  File "/config/appdaemon/apps/qolsysgw/qolsys/socket.py", line 105, in listen
    await self._callback(event)
  File "/config/appdaemon/apps/qolsysgw/gateway.py", line 165, in qolsys_event_callback
    payload=event.raw_str,
AttributeError: 'NoneType' object has no attribute 'raw_str'
```

If I find some time, I'm happy to take a look at this myself as well. Just wanted to make sure nobody else was first :)

**Comment by XaF** [comment]
Hey @kevin-david ! Thanks for the report and good catch!
Seems that my method to find subclasses is failing for the `SmokeDetector` - it's related to the normalization of the sensor type which converts to `Smokedetector` instead (i.e. losing one capital), will work on fixing this!

**Comment by XaF** [comment]
Could you try out [the `dev` branch](https://github.com/XaF/qolsysgw/tree/dev) ? I pushed a fix that should be solving your issue, but I cannot try it out myself locally yet (and don't have a smoke detector connected either)

**Comment by kevin-david** [comment]
Nice, it works!! Thanks for the quick fix!

![image](https://user-images.githubusercontent.com/1923186/147844783-f3f906de-25b2-4f7c-b0e1-8017cec2c3e7.png)

**Comment by XaF** [comment]
Thanks for testing and confirming! I just merged the fix in the main branch :)
