### ISSUE TITLE
Show better error message when not finding the `mqtt_plugin_cfg` using the configured namespace

### ISSUE THREAD

**Issue by XaF** [XaF/qolsysgw#10]
Currently, this returns the following: (from https://github.com/XaF/qolsysgw/issues/8#issuecomment-1025898800)

```
2022-01-31 16:10:58.845177 ERROR qolsys_panel: Task exception was never retrieved
future: <Task finished name='Task-237' coro=<QolsysSocket.listen() done, defined at /config/appdaemon/apps/qolsysgw/qolsys/socket.py:60> exception=AttributeError("'NoneType' object has no attribute 'get'")>
Traceback (most recent call last):
File "/config/appdaemon/apps/qolsysgw/qolsys/socket.py", line 119, in listen
await self._disconnected_callback()
File "/config/appdaemon/apps/qolsysgw/gateway.py", line 158, in qolsys_disconnected_callback
self._factory.wrap(self._state).set_unavailable()
File "/config/appdaemon/apps/qolsysgw/mqtt/updater.py", line 500, in wrap
return klass(obj, *self._args, **self._kwargs)
File "/config/appdaemon/apps/qolsysgw/mqtt/updater.py", line 205, in init
super().init(*args, **kwargs)
File "/config/appdaemon/apps/qolsysgw/mqtt/updater.py", line 86, in init
self._birth_topic = mqtt_plugin_cfg.get('birth_topic')
AttributeError: 'NoneType' object has no attribute 'get'
```

We would want a better error message, and maybe to fail earlier if we're not able to get MQTT plugin configuration ? Or maybe just a warning ?

**Comment by PerfectBake420** [comment]
I tried to copy a more complete log as some of it disappears as others lines are added. I know the times are off due to different restarts. I believe I got it all line by line

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: AppDaemon 4
 Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 0.8.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 7.2  (amd64 / qemux86-64)
 Home Assistant Core: 2021.12.10
 Home Assistant Supervisor: 2022.01.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] appdaemon.sh: executing... 
[cont-init.d] appdaemon.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[10:33:30] INFO: Starting AppDaemon...
2022-02-01 16:34:11.701798 INFO AppDaemon: AppDaemon Version 4.2.1 starting
2022-02-01 16:34:11.704541 INFO AppDaemon: Python version is 3.9.7
2022-02-01 16:34:11.705622 INFO AppDaemon: Configuration read from: /config/appdaemon/appdaemon.yaml
2022-02-01 16:34:11.706496 INFO AppDaemon: Added log: AppDaemon
2022-02-01 16:34:11.707970 INFO AppDaemon: Added log: Error
2022-02-01 16:34:11.709130 INFO AppDaemon: Added log: Access
2022-02-01 16:34:11.710033 INFO AppDaemon: Added log: Diag
2022-02-01 16:34:11.789276 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin

2022-02-01 16:34:50.864163 INFO AppDaemon: Adding /config/appdaemon/apps/qolsysgw to module import path
2022-02-01 16:34:50.865534 INFO AppDaemon: Adding /config/appdaemon/apps/qolsysgw/mqtt to module import path
2022-02-01 16:34:50.867361 INFO AppDaemon: Adding /config/appdaemon/apps/qolsysgw/qolsys to module import path
2022-02-01 16:34:50.899102 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/hello.py - ignoring
2022-02-01 16:34:50.902308 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/qolsysgw/gateway.py
2022-02-01 16:34:50.989885 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/mqtt/updater.py - ignoring
2022-02-01 16:34:50.994063 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/mqtt/exceptions.py - ignoring
2022-02-01 16:34:50.996531 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/mqtt/utils.py - ignoring
2022-02-01 16:34:51.000027 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/mqtt/listener.py - ignoring
2022-02-01 16:34:51.003199 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/observable.py - ignoring
2022-02-01 16:34:51.006282 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/exceptions.py - ignoring
2022-02-01 16:34:51.010654 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/utils.py - ignoring
2022-02-01 16:34:51.014382 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/sensors.py - ignoring
2022-02-01 16:34:51.016844 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/partition.py - ignoring
2022-02-01 16:34:51.020074 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/events.py - ignoring
2022-02-01 16:34:51.022888 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/state.py - ignoring
2022-02-01 16:34:51.026043 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/config.py - ignoring
2022-02-01 16:34:51.028557 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/socket.py - ignoring
2022-02-01 16:34:51.031335 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/control.py - ignoring
2022-02-01 16:34:51.034196 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/actions.py - ignoring
2022-02-01 16:34:51.037101 INFO AppDaemon: Initializing app qolsys_panel using class QolsysGateway from module gateway
2022-02-01 16:34:51.289742 INFO qolsys_panel: Starting
2022-02-01 16:34:51.299662 ERROR qolsys_panel: Error setting state unavailable; pursuing
Traceback (most recent call last):
  File "/config/appdaemon/apps/qolsysgw/gateway.py", line 87, in initialize
    self._factory.wrap(self._state).set_unavailable()
  File "/config/appdaemon/apps/qolsysgw/mqtt/updater.py", line 500, in wrap
    return klass(obj, *self._args, **self._kwargs)
  File "/config/appdaemon/apps/qolsysgw/mqtt/updater.py", line 205, in __init__
    super().__init__(*args, **kwargs)
  File "/config/appdaemon/apps/qolsysgw/mqtt/updater.py", line 86, in __init__
    self._birth_topic = mqtt_plugin_cfg.get('birth_topic')
AttributeError: 'NoneType' object has no attribute 'get'
2022-02-01 16:34:51.312930 DEBUG qolsys_panel: Registering <mqtt.updater.MqttUpdater object at 0x7fc658bd5640> to <qolsys.state.QolsysState object at 0x7fc65914de20> updates
2022-02-01 16:34:51.319915 INFO qolsys_panel: Started
2022-02-01 16:34:51.323337 INFO AppDaemon: App initialization complete
2022-02-01 16:34:51.326175 DEBUG qolsys_panel: call_service: mqtt/subscribe, {'namespace': 'mqtt', 'topic': 'qolsys/qolsys_panel/event'}
2022-02-01 16:34:51.327705 DEBUG qolsys_panel: call_service: mqtt/subscribe, {'namespace': 'mqtt', 'topic': 'homeassistant/alarm_control_panel/qolsys_panel/set'}
2022-02-01 16:34:51.339020 ERROR qolsys_panel: Task exception was never retrieved
future: <Task finished name='Task-196' coro=<ADAPI.call_service() done, defined at /usr/lib/python3.9/site-packages/appdaemon/adapi.py:1677> exception=NamespaceException('Unknown namespace (%s) in call_service from %s', 'mqtt', 'qolsys_panel')>
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/appdaemon/adapi.py", line 1748, in call_service
    return await self.AD.services.call_service(namespace, d, s, kwargs)
  File "/usr/lib/python3.9/site-packages/appdaemon/services.py", line 152, in call_service
    raise NamespaceException("Unknown namespace (%s) in call_service from %s", namespace, name)
NamespaceException: ('Unknown namespace (%s) in call_service from %s', 'mqtt', 'qolsys_panel')
2022-02-01 16:34:51.342691 DEBUG qolsys_panel: Calling listen_event for qolsys_panel
2022-02-01 16:34:51.348861 ERROR qolsys_panel: Task exception was never retrieved
future: <Task finished name='Task-198' coro=<ADAPI.call_service() done, defined at /usr/lib/python3.9/site-packages/appdaemon/adapi.py:1677> exception=NamespaceException('Unknown namespace (%s) in call_service from %s', 'mqtt', 'qolsys_panel')>
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/appdaemon/adapi.py", line 1748, in call_service
    return await self.AD.services.call_service(namespace, d, s, kwargs)
  File "/usr/lib/python3.9/site-packages/appdaemon/services.py", line 152, in call_service
    raise NamespaceException("Unknown namespace (%s) in call_service from %s", namespace, name)
NamespaceException: ('Unknown namespace (%s) in call_service from %s', 'mqtt', 'qolsys_panel')
2022-02-01 16:34:51.352891 DEBUG qolsys_panel: Calling listen_event for qolsys_panel
2022-02-01 16:34:51.369402 INFO qolsys_panel: Establishing connection to 192.168.112.5:12345
2022-02-01 16:34:51.783421 DEBUG qolsys_panel: Sending: {"nonce": "qolsys", "source": "C4", "version": 0, "action": "INFO", "info_type": "SUMMARY", "token": "e86rpe"}
2022-02-01 16:34:51.792748 DEBUG qolsys_panel: Qolsys callback for connection event
2022-02-01 16:34:51.798561 ERROR qolsys_panel: error while listening
Traceback (most recent call last):
  File "/config/appdaemon/apps/qolsysgw/qolsys/socket.py", line 78, in listen
    await self._connected_callback()
  File "/config/appdaemon/apps/qolsysgw/gateway.py", line 151, in qolsys_connected_callback
    self._factory.wrap(self._state).set_available()
  File "/config/appdaemon/apps/qolsysgw/mqtt/updater.py", line 500, in wrap
    return klass(obj, *self._args, **self._kwargs)
  File "/config/appdaemon/apps/qolsysgw/mqtt/updater.py", line 205, in __init__
    super().__init__(*args, **kwargs)
  File "/config/appdaemon/apps/qolsysgw/mqtt/updater.py", line 86, in __init__
    self._birth_topic = mqtt_plugin_cfg.get('birth_topic')
AttributeError: 'NoneType' object has no attribute 'get'
2022-02-01 16:34:51.807201 DEBUG qolsys_panel: Qolsys callback for disconnection event
2022-02-01 16:34:51.815923 ERROR qolsys_panel: Task exception was never retrieved
future: <Task finished name='Task-237' coro=<QolsysSocket.listen() done, defined at /config/appdaemon/apps/qolsysgw/qolsys/socket.py:60> exception=AttributeError("'NoneType' object has no attribute 'get'")>
Traceback (most recent call last):
  File "/config/appdaemon/apps/qolsysgw/qolsys/socket.py", line 119, in listen
    await self._disconnected_callback()
  File "/config/appdaemon/apps/qolsysgw/gateway.py", line 158, in qolsys_disconnected_callback
    self._factory.wrap(self._state).set_unavailable()
  File "/config/appdaemon/apps/qolsysgw/mqtt/updater.py", line 500, in wrap
    return klass(obj, *self._args, **self._kwargs)
  File "/config/appdaemon/apps/qolsysgw/mqtt/updater.py", line 205, in __init__
    super().__init__(*args, **kwargs)
  File "/config/appdaemon/apps/qolsysgw/mqtt/updater.py", line 86, in __init__
    self._birth_topic = mqtt_plugin_cfg.get('birth_topic')
AttributeError: 'NoneType' object has no attribute 'get'
