### ISSUE TITLE
Qolsys IQ 4 Panel not connecting on port 12345, but something is happening on port 9200

### ISSUE THREAD

**Issue by ChrisTolmeijer** [XaF/qolsysgw#106]
I have the Qolsys IQ 4 Panel, version 4.2.1 managed through alarm.com. I followed all the installation steps, and my dealer created a control4 access token for me. But when I'm trying to connect it doesn't work:

```
2023-05-06 10:13:44.279277 INFO hello_world: Hello from AppDaemon
2023-05-06 10:13:44.279836 INFO hello_world: You are now ready to run Apps!
2023-05-06 10:13:44.280354 INFO AppDaemon: Calling initialize() for qolsys_panel
2023-05-06 10:13:44.283188 INFO qolsys_panel: Starting
2023-05-06 10:13:44.285325 WARNING qolsys_panel: No mac address found for '192.168.1.165'
2023-05-06 10:13:44.287990 INFO qolsys_panel: Started
2023-05-06 10:13:44.288454 INFO AppDaemon: App initialization complete
2023-05-06 10:13:44.295832 INFO qolsys_panel: Establishing connection to 192.168.1.165:12345
2023-05-06 10:13:44.404151 ERROR qolsys_panel: error while listening
Traceback (most recent call last):
  File "/config/appdaemon/apps/qolsysgw/qolsys/socket.py", line 72, in listen
    reader, writer = await asyncio.open_connection(
  File "/usr/lib/python3.10/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.1.165', 12345)
2023-05-06 10:13:44.406228 INFO qolsys_panel: sleeping 1 second(s) before reconnecting
```

I noticed the `No mac address found` error. I verified I got the right IP address and it just looks like the panel is not responding to any arp requests, tried `arp 192.168.1.165` from multiple computers but none get a mac address resolved. From looking at the code quickly, not having the mac address isn't a breaking feature. So I moved on.

Then I tried to telnet into the panel using the default port provided in the documentation (`telnet 192.168.1.165 12345`) but the connection is refused.

After googling I found someone say that their panel port was changed to 9200:
https://community.hubitat.com/t/release-qolsys-iq-alarm-panel-drivers/85139/7

Indeed when I try the same telnet command on that port, I get an open connection `telnet 192.168.1.165 9200`. So I set the `panel_port: 9200` configuration in the yaml. But I now I get the following connection issue. 
```
2023-05-06 10:32:46.747485 INFO qolsys_panel: Establishing connection to 192.168.1.165:9200
2023-05-06 10:32:51.805577 ERROR qolsys_panel: error while listening
Traceback (most recent call last):
  File "/config/appdaemon/apps/qolsysgw/qolsys/socket.py", line 72, in listen
    reader, writer = await asyncio.open_connection(
  File "/usr/lib/python3.10/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1103, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1133, in _create_connection_transport
    await waiter
ConnectionResetError: 
2023-05-06 10:32:51.807649 INFO qolsys_panel: sleeping 1 second(s) before reconnecting
```

I don't get much further by following the discussion in that link that I posted. Seems that some people were on version 4.0.1 and after manually updating to 4.1.0 were able to successfully connect. However, I'm on version 4.2.1, so i assume it's not a version issue.

Is anyone familiar with this issue?

**Comment by XaF** [comment]
I am on 4.2.1 too, and the first time I setup the panel I had to reset the token (and restart) a few times before things worked. No idea why. But since it worked, no issue.

I didn't have to change the port, I believe something else is on 9200 but the control4 interface stays on 12345.

You might want to try rolling the token, restart the panel, check with the new token, and try this a few times (had to do it 3-4 times if I remember correctly, very "have you tried turning it off and on again", I know!)

**Comment by ChrisTolmeijer** [comment]
Thanks for the quick reply. I don't have the dealer code so that would require them to come out unfortunately. Since the port seems to be closed to any kind of connection, I wonder if you retrying a few times trick was necessary to actually enable the service. Maybe I should actually try to turn off and on the device.

**Comment by XaF** [comment]
If I remember correctly, during some of the reboots the service was "turned off" for some reason. Maybe call your company and ask them for the code?

**Comment by ChrisTolmeijer** [comment]
Ok, great success, I guessed my way in. Apparently there was a 6 digit dealer code. Control4 was disabled, it worked as soon as I enabled it and rebooted. Thank you for your help.
