### ISSUE TITLE
No Sensor Data Being Pulled In- Error while listening

### ISSUE THREAD

**Issue by teek541** [XaF/qolsysgw#120]
### Before submitting this form

- [X] I have checked that there hasn't been a similar issue submitted in the past

- [X] I have updated the issue title to something relevant and clear to understand the bug I'm facing

### Description of the bug

I have everything configured correctly, but it seems like it's not listening to the panel and pulling sensor data.

### Expected behavior

I'm expecting to have an active MQTT session with the Quolsys IQ 4 Pannel and pull in sensor data into Home Assistant.

### DEBUG logs

I'm going to apologize as I'm relatively new to Home Assistant and brand new to AppDaemon and MQTT.  I'm pretty sure I have it setup correctly, it wasn't connecting to my broker before and now it is.  Listening to my broker all I'm seeing is the following:

Message 1 received on homeassistant/alarm_control_panel/qolsys_panel/availability at 00:51:
offline
QoS: 0 - Retain: true
Message 0 received on mqtt-client/status at 00:51:
online

I think it's erroring out on actually connecting/listening to the panel?

apps.yaml

qolsys_panel:
  log_level: DEBUG
  module: gateway
  class: QolsysGateway
  panel_host: 192.168.XX.XXX
  panel_mac: 3c:31:78:b8:XX:XX
  panel_token: !secret panel_token
  panel_user_code: !secret panel_user_code
  discovery_topic: homeassistant
  namespace: mqtt
  password: !secret mqtt_password
  
  
  appdaemon.yaml
 
 secrets: /config/secrets.yaml
appdaemon:
  latitude: XX
  longitude: XX
  elevation: 2
  time_zone: America/Los_Angeles
  plugins:
    HASS:
      type: hass
      ha_url: http://homeassistant.local:8123
      token: !secret HASS_token
    MQTT:
        type: mqtt
        namespace: mqtt
        verbose: True
        client_host: core-mosquitto
        client_port: 1883
        client_user: hamqtt
        client_password: !secret mqtt_password
        event_name: MQTT_EVENT
        client_topics: NONE

http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:
  
  
  
 Logs:
   Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 0.13.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.4  (aarch64 / yellow)
 Home Assistant Core: 2023.8.1
 Home Assistant Supervisor: 2023.07.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-appdaemon: starting
s6-rc: info: service init-appdaemon successfully started
s6-rc: info: service appdaemon: starting
s6-rc: info: service appdaemon successfully started
s6-rc: info: service legacy-services: starting
[00:46:40] INFO: Starting AppDaemon...
s6-rc: info: service legacy-services successfully started
2023-08-06 00:46:47.268261 INFO AppDaemon: AppDaemon Version 4.4.2 starting
2023-08-06 00:46:47.268760 INFO AppDaemon: Python version is 3.11.4
2023-08-06 00:46:47.269138 INFO AppDaemon: Configuration read from: /config/appdaemon/appdaemon.yaml
2023-08-06 00:46:47.269468 INFO AppDaemon: Added log: AppDaemon
2023-08-06 00:46:47.269828 INFO AppDaemon: Added log: Error
2023-08-06 00:46:47.270156 INFO AppDaemon: Added log: Access
2023-08-06 00:46:47.270465 INFO AppDaemon: Added log: Diag
2023-08-06 00:46:47.705955 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2023-08-06 00:46:48.121624 INFO HASS: HASS Plugin Initializing
2023-08-06 00:46:48.121987 INFO HASS: HASS Plugin initialization complete
2023-08-06 00:46:48.122464 INFO AppDaemon: Loading Plugin MQTT using class MqttPlugin from module mqttplugin
2023-08-06 00:46:48.275597 INFO MQTT: MQTT Plugin Initializing
2023-08-06 00:46:48.275978 INFO MQTT: Using 'mqtt-client/status' as Will Topic
2023-08-06 00:46:48.276246 INFO MQTT: Using 'mqtt-client/status' as Birth Topic
2023-08-06 00:46:48.276665 INFO MQTT: Using appdaemon_mqtt_client as Client ID
2023-08-06 00:46:48.277688 INFO AppDaemon: Initializing HTTP
2023-08-06 00:46:48.278426 INFO AppDaemon: Using 'ws' for event stream
2023-08-06 00:46:48.284993 INFO AppDaemon: Starting API
2023-08-06 00:46:48.290003 INFO AppDaemon: Starting Admin Interface
2023-08-06 00:46:48.290662 INFO AppDaemon: Starting Dashboards
2023-08-06 00:46:48.324348 INFO HASS: Connected to Home Assistant 2023.8.1
2023-08-06 00:46:48.354009 INFO MQTT: Connected to Broker at URL core-mosquitto:1883
2023-08-06 00:46:48.356645 WARNING AppDaemon: App 'secrets' missing 'class' or 'module' entry - ignoring
2023-08-06 00:46:48.362226 INFO AppDaemon: App 'hello_world' added
2023-08-06 00:46:48.364230 INFO AppDaemon: Got initial state from namespace mqtt
2023-08-06 00:46:48.364954 INFO MQTT: MQTT Plugin initialization complete
2023-08-06 00:46:48.369237 INFO AppDaemon: App 'qolsys_panel' added
2023-08-06 00:46:48.370860 INFO AppDaemon: Found 2 active apps
2023-08-06 00:46:48.371795 INFO AppDaemon: Found 0 inactive apps
2023-08-06 00:46:48.372396 INFO AppDaemon: Found 0 global libraries
2023-08-06 00:46:48.373502 INFO AppDaemon: Starting Apps with 2 workers and 2 pins
2023-08-06 00:46:48.376273 INFO AppDaemon: Running on port 5050
2023-08-06 00:46:48.438649 INFO HASS: Evaluating startup conditions
2023-08-06 00:46:48.444894 INFO HASS: Startup condition met: hass state=RUNNING
2023-08-06 00:46:48.445750 INFO HASS: All startup conditions met
2023-08-06 00:46:48.457470 INFO AppDaemon: New client Admin Client connected
2023-08-06 00:46:48.490218 INFO AppDaemon: Got initial state from namespace default
2023-08-06 00:46:50.388841 INFO AppDaemon: Scheduler running in realtime
2023-08-06 00:46:50.408689 INFO AppDaemon: Adding /config/appdaemon/apps to module import path
2023-08-06 00:46:50.409429 INFO AppDaemon: Adding /config/appdaemon/apps/qolsysgw to module import path
2023-08-06 00:46:50.410159 INFO AppDaemon: Adding /config/appdaemon/apps/qolsysgw/mqtt to module import path
2023-08-06 00:46:50.410911 INFO AppDaemon: Adding /config/appdaemon/apps/qolsysgw/qolsys to module import path
2023-08-06 00:46:50.439539 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/hello.py
2023-08-06 00:46:50.512344 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/qolsysgw/gateway.py
2023-08-06 00:46:50.632980 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/mqtt/updater.py - ignoring
2023-08-06 00:46:50.635447 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/mqtt/listener.py - ignoring
2023-08-06 00:46:50.638544 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/mqtt/utils.py - ignoring
2023-08-06 00:46:50.641552 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/mqtt/exceptions.py - ignoring
2023-08-06 00:46:50.644482 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/config.py - ignoring
2023-08-06 00:46:50.647696 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/events.py - ignoring
2023-08-06 00:46:50.650894 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/control.py - ignoring
2023-08-06 00:46:50.653992 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/utils.py - ignoring
2023-08-06 00:46:50.657266 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/actions.py - ignoring
2023-08-06 00:46:50.660508 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/socket.py - ignoring
2023-08-06 00:46:50.663676 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/state.py - ignoring
2023-08-06 00:46:50.666806 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/sensors.py - ignoring
2023-08-06 00:46:50.670186 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/partition.py - ignoring
2023-08-06 00:46:50.673232 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/observable.py - ignoring
2023-08-06 00:46:50.676332 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/exceptions.py - ignoring
2023-08-06 00:46:50.678993 INFO AppDaemon: Loading app hello_world using class HelloWorld from module hello
2023-08-06 00:46:50.684058 INFO AppDaemon: Loading app qolsys_panel using class QolsysGateway from module gateway
2023-08-06 00:46:50.690031 INFO AppDaemon: Calling initialize() for hello_world
2023-08-06 00:46:50.818959 INFO hello_world: Hello from AppDaemon
2023-08-06 00:46:50.821221 INFO hello_world: You are now ready to run Apps!
2023-08-06 00:46:50.823715 INFO AppDaemon: Calling initialize() for qolsys_panel
2023-08-06 00:46:50.841802 INFO qolsys_panel: Starting
2023-08-06 00:46:50.861142 DEBUG qolsys_panel: Registering <mqtt.updater.MqttUpdater object at 0x7f7c010850> to <qolsys.state.QolsysState object at 0x7f7c19bf50> updates
2023-08-06 00:46:50.872234 INFO qolsys_panel: Started
2023-08-06 00:46:50.874842 INFO AppDaemon: App initialization complete
2023-08-06 00:46:50.879612 DEBUG qolsys_panel: call_service: mqtt/publish, {'namespace': 'mqtt', 'retain': True, 'topic': 'homeassistant/alarm_control_panel/qolsys_panel/availability', 'payload': 'offline'}
2023-08-06 00:46:50.881407 DEBUG qolsys_panel: call_service: mqtt/subscribe, {'namespace': 'mqtt', 'topic': 'qolsys/qolsys_panel/event'}
2023-08-06 00:46:50.883048 DEBUG qolsys_panel: call_service: mqtt/subscribe, {'namespace': 'mqtt', 'topic': 'homeassistant/alarm_control_panel/qolsys_panel/set'}
2023-08-06 00:46:50.886503 DEBUG qolsys_panel: Calling listen_event for qolsys_panel
2023-08-06 00:46:50.914059 INFO qolsys_panel: Previous message repeated 1 times
2023-08-06 00:46:50.914623 INFO qolsys_panel: Establishing connection to 192.168.XX.XXX:12345
2023-08-06 00:49:01.423525 ERROR qolsys_panel: error while listening
Traceback (most recent call last):
  File "/config/appdaemon/apps/qolsysgw/qolsys/socket.py", line 72, in listen
    reader, writer = await asyncio.open_connection(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 634, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 674, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('192.168.XX.XXX', 12345)
2023-08-06 00:49:01.434453 DEBUG qolsys_panel: Qolsys callback for disconnection event
2023-08-06 00:49:01.452203 INFO qolsys_panel: sleeping 1 second(s) before reconnecting
2023-08-06 00:49:01.453654 DEBUG qolsys_panel: call_service: mqtt/publish, {'namespace': 'mqtt', 'retain': True, 'topic': 'homeassistant/alarm_control_panel/qolsys_panel/availability', 'payload': 'offline'}
2023-08-06 00:49:02.458164 INFO qolsys_panel: Establishing connection to 192.168.XX.XXX:12345

**Comment by teek541** [comment]
Okay, so looking back at a 600+ post discussion I saw that some people were having an issue connecting to their panel and it was a problem with control 4.  Mine was still enabled and the token was the same.  I disabled it, reenabled it, and now I can see the MQTT messages in the log.  However, the sensor data is not being created in MQTT.  I made sure that the discovery topics match.

I'm still getting this in my log, I'm not sure if this has anything to do with it.
2023-08-06 11:22:58.439687 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/mqtt/updater.py - ignoring
2023-08-06 11:22:58.441532 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/mqtt/listener.py - ignoring
2023-08-06 11:22:58.443207 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/mqtt/utils.py - ignoring
2023-08-06 11:22:58.444974 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/mqtt/exceptions.py - ignoring
2023-08-06 11:22:58.446937 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/config.py - ignoring
2023-08-06 11:22:58.449262 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/events.py - ignoring
2023-08-06 11:22:58.451385 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/control.py - ignoring
2023-08-06 11:22:58.453438 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/utils.py - ignoring
2023-08-06 11:22:58.455425 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/actions.py - ignoring
2023-08-06 11:22:58.457315 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/socket.py - ignoring
2023-08-06 11:22:58.459301 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/state.py - ignoring
2023-08-06 11:22:58.461338 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/sensors.py - ignoring
2023-08-06 11:22:58.463349 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/partition.py - ignoring
2023-08-06 11:22:58.465375 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/observable.py - ignoring
2023-08-06 11:22:58.467426 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/exceptions.py - ignoring


I'm now getting a bunch of other messages that look like this:

2023-08-06 11:22:58.481450 INFO AppDaemon: Loading app hello_world using class HelloWorld from module hello
2023-08-06 11:22:58.488432 INFO AppDaemon: Loading app qolsys_panel using class QolsysGateway from module gateway
2023-08-06 11:22:58.492928 INFO AppDaemon: Calling initialize() for hello_world
2023-08-06 11:22:58.619911 INFO hello_world: Hello from AppDaemon
2023-08-06 11:22:58.622284 INFO hello_world: You are now ready to run Apps!
2023-08-06 11:22:58.624458 INFO AppDaemon: Calling initialize() for qolsys_panel
2023-08-06 11:22:58.640940 INFO qolsys_panel: Starting
2023-08-06 11:22:58.651610 DEBUG qolsys_panel: Registering <mqtt.updater.MqttUpdater object at 0x7f845e3690> to <qolsys.state.QolsysState object at 0x7f856665d0> updates
2023-08-06 11:22:58.662663 INFO qolsys_panel: Started
2023-08-06 11:22:58.664330 INFO AppDaemon: App initialization complete
2023-08-06 11:22:58.665927 DEBUG qolsys_panel: call_service: mqtt/publish, {'namespace': 'mqtt', 'retain': True, 'topic': 'homeassistant/alarm_control_panel/qolsys_panel/availability', 'payload': 'offline'}
2023-08-06 11:22:58.666549 DEBUG qolsys_panel: call_service: mqtt/subscribe, {'namespace': 'mqtt', 'topic': 'qolsys/qolsys_panel/event'}
2023-08-06 11:22:58.667486 DEBUG qolsys_panel: call_service: mqtt/subscribe, {'namespace': 'mqtt', 'topic': 'homeassistant/alarm_control_panel/qolsys_panel/set'}
2023-08-06 11:22:58.673330 DEBUG qolsys_panel: Calling listen_event for qolsys_panel
2023-08-06 11:22:58.689639 INFO qolsys_panel: Previous message repeated 1 times
2023-08-06 11:22:58.690051 INFO qolsys_panel: Establishing connection to 192.168.20.223:12345
2023-08-06 11:22:58.782116 DEBUG qolsys_panel: Sending: {"nonce": "qolsys", "source": "C4", "version": 0, "action": "INFO", "info_type": "SUMMARY", "token": "XXXXXX"}
2023-08-06 11:22:58.789632 DEBUG qolsys_panel: Qolsys callback for connection event
2023-08-06 11:22:58.794921 DEBUG qolsys_panel: call_service: mqtt/publish, {'namespace': 'mqtt', 'retain': True, 'topic': 'homeassistant/sensor/qolsys_panel_last_error/config', 'payload': '{"name": "Qolsys Panel Last Error", "device_class": "timestamp", "state_topic": "homeassistant/sensor/qolsys_panel_last_error/state", "availability_mode": "all", "availability": [{"topic": "homeassistant/alarm_control_panel/qolsys_panel/availability", "payload_available": "online", "payload_not_available": "offline"}, {"topic": "mqtt-client/status", "payload_available": "online", "payload_not_available": "offline"}], "json_attributes_topic": "homeassistant/sensor/qolsys_panel_last_error/attributes", "unique_id": "qolsys_panel_last_error", "device": {"name": "Qolsys Panel", "identifiers": ["qolsys_panel"], "manufacturer": "Qolsys", "model": "IQ Panel 2+", "connections": [["mac", "3c:31:78:b8:XX:XX"]]}}'}
2023-08-06 11:22:58.795679 DEBUG qolsys_panel: call_service: mqtt/publish, {'namespace': 'mqtt', 'retain': True, 'topic': 'homeassistant/alarm_control_panel/qolsys_panel/availability', 'payload': 'online'}
2023-08-06 11:22:58.796150 DEBUG qolsys_panel: call_service: mqtt/publish, {'namespace': 'mqtt', 'retain': True, 'topic': 'homeassistant/sensor/qolsys_panel_last_error/state', 'payload': None}
2023-08-06 11:22:58.796603 DEBUG qolsys_panel: call_service: mqtt/publish, {'namespace': 'mqtt', 'retain': True, 'topic': 'homeassistant/sensor/qolsys_panel_last_error/attributes', 'payload': '{"type": null, "desc": null}'}
2023-08-06 11:22:58.818947 DEBUG qolsys_panel: Data received (len: 3): ACK
2023-08-06 11:22:58.825970 DEBUG qolsys_panel: ACK - ignoring.
2023-08-06 11:22:58.837661 DEBUG qolsys_panel: Data received (len: 4138): {"event":"INFO","info_type":"SUMMARY","partition_list":[{"partition_id":0,"name":"SYSTEM","status":"DISARM","secure_arm":false,"zone_list":[{"id":"8F71A0","type":"TakeoverModule","name":"Hardwire Translator","group":"takeovermodule","status":"Closed","state":"0","zone_id":1,"zone_physical_type":13,"zone_alarm_type":0,"zone_type":18,"partition_id":0},{"id":"6E034D","type":"Motion","name":"Dining Motion","group":"awayinstantmotion","status":"Open","state":"0","zone_id":2,"zone_physical_type":2,"zone_alarm_type":3,"zone_type":2,"partition_id":0},{"id":"B5D2A9","type":"Door_Window","name":"Sliding Door","group":"instantperimeter","status":"Closed","state":"0","zone_id":3,"zone_physical_type":1,"zone_alarm_type":3,"zone_type":1,"partition_id":0},{"id":"8F71A1","type":"Door_Window","name":"Front Door","group":"entryexitdelay","status":"Closed","state":"0","zone_id":4,"zone_physical_type":1,"zone_alarm_type":3,"zone_type":1,"partition_id":0},{"id":"8F71A3","type":"Door_Window","name":"Front Window","group":"instantperimeter","status":"Closed","state":"0","zone_id":5,"zone_physical_type":1,"zone_alarm_type":3,"zone_type":1,"partition_id":0},{"id":"8F71A4","type":"Door_Window","name":"Dining Room Window","group":"instantperimeter","status":"Closed","state":"0","zone_id":6,"zone_physical_type":1,"zone_alarm_type":3,"zone_type":1,"partition_id":0},{"id":"8F71A6","type":"Door_Window","name":"Living Room Window East","group":"instantperimeter","status":"Closed","state":"0","zone_id":7,"zone_physical_type":1,"zone_alarm_type":3,"zone_type":1,"partition_id":0},{"id":"8F71A7","type":"Door_Window","name":"Living Room Window West","group":"instantperimeter","status":"Closed","state":"0","zone_id":8,"zone_physical_type":1,"zone_alarm_type":3,"zone_type":1,"partition_id":0},{"id":"8F71A8","type":"Door_Window","name":"Kitchen Window","group":"instantperimeter","status":"Closed","state":"0","zone_id":9,"zone_physical_type":1,"zone_alarm_type":3,"zone_type":1,"partition_id":0},{"id":"8F71A2","type":"Door_Window","name":"Garage Door","group":"entryexitdelay","status":"Closed","state":"0","zone_id":10,"zone_physical_type":1,"zone_alarm_type":3,"zone_type":1,"partition_id":0},{"id":"8F71A9","type":"Door_Window","name":"Garage Side","group":"instantperimeter","status":"Closed","state":"0","zone_id":11,"zone_physical_type":1,"zone_alarm_type":3,"zone_type":1,"partition_id":0},{"id":"8F71AA","type":"Door_Window","name":"Front Bedroom Widow","group":"instantperimeter","status":"Closed","state":"0","zone_id":12,"zone_physical_type":1,"zone_alarm_type":3,"zone_type":1,"partition_id":0},{"id":"8F71AB","type":"Door_Window","name":"Back Bedroom Window","group":"instantperimeter","status":"Closed","state":"0","zone_id":13,"zone_physical_type":1,"zone_alarm_type":3,"zone_type":1,"partition_id":0},{"id":"8F71AD","type":"Door_Window","name":"Master Bedroom Window","group":"instantperimeter","status":"Closed","state":"0","zone_id":14,"zone_physical_type":1,"zone_alarm_type":3,"zone_type":1,"partition_id":0},{"id":"8F71AE","type":"Door_Window","name":"Office Window","group":"instantperimeter","status":"Closed","state":"0","zone_id":15,"zone_physical_type":1,"zone_alarm_type":3,"zone_type":1,"partition_id":0},{"id":"8F71AC","type":"Door_Window","name":"Master Bathroom Window","group":"instantperimeter","status":"Closed","state":"0","zone_id":16,"zone_physical_type":1,"zone_alarm_type":3,"zone_type":1,"partition_id":0},{"id":"SWG1","type":"Panel Glass Break","name":"Panel Glass Break","group":"glassbreakawayonly","status":"Closed","state":"0","zone_id":17,"zone_physical_type":1,"zone_alarm_type":0,"zone_type":116,"partition_id":0},{"id":"SWPM1","type":"Panel Motion","name":"Panel Motion","group":"safetymotion","status":"Closed","state":"0","zone_id":18,"zone_physical_type":1,"zone_alarm_type":3,"zone_type":119,"partition_id":0},{"id":"8F71A5","type":"Motion","name":"Motion Detector","group":"awayinstantinteriormotion","status":"Closed","state":"0","zone_id":19,"zone_physical_type":2,"zone_alarm_type":3,"zone_type":2,"partition_id":0}]}],"nonce":"qolsys","requestID":"f5ab1524-cd16-4444-b84b-9cd2bb05dcf5"}
2023-08-06 11:22:58.852208 DEBUG qolsys_panel: Notifying <QolsysPartition id=0 name=SYSTEM status=DISARM secure_arm=False sensors(1)=[<QolsysSensorTakeoverModule id=8F71A0 name=Hardwire Translator group=takeovermodule status=Closed state=0 zone_id=1 zone_type=18 zone_physical_type=13 zone_alarm_type=0 partition_id=0>]> observers with: {'change': 'add_sensor', 'new_value': <qolsys.sensors.QolsysSensorTakeoverModule object at 0x7f866f8910>}
2023-08-06 11:22:58.888436 DEBUG qolsys_panel: Notifying <QolsysPartition id=0 name=SYSTEM status=DISARM secure_arm=False sensors(2)=[<QolsysSensorTakeoverModule id=8F71A0 name=Hardwire Translator group=takeovermodule status=Closed state=0 zone_id=1 zone_type=18 zone_physical_type=13 zone_alarm_type=0 partition_id=0>, <QolsysSensorMotion id=6E034D name=Dining Motion group=awayinstantmotion status=Open state=0 zone_id=2 zone_type=2 zone_physical_type=2 zone_alarm_type=3 partition_id=0>]> observers with: {'change': 'add_sensor', 'new_value': <qolsys.sensors.QolsysSensorMotion object at 0x7f83330f90>}
2023-08-06 11:22:58.895781 DEBUG qolsys_panel: Notifying <QolsysPartition id=0 name=SYSTEM status=DISARM secure_arm=False sensors(3)=[<QolsysSensorTakeoverModule id=8F71A0 name=Hardwire Translator group=takeovermodule status=Closed state=0 zone_id=1 zone_type=18 zone_physical_type=13 zone_alarm_type=0 partition_id=0>, <QolsysSensorMotion id=6E034D name=Dining Motion group=awayinstantmotion status=Open state=0 zone_id=2 zone_type=2 zone_physical_type=2 zone_alarm_type=3 partition_id=0>, <QolsysSensorDoorWindow id=B5D2A9 name=Sliding Door group=instantperimeter status=Closed state=0 zone_id=3 zone_type=1 zone_physical_type=1 zone_alarm_type=3 partition_id=0>]> observers with: {'change': 'add_sensor', 'new_value': <qolsys.sensors.QolsysSensorDoorWindow object at 0x7f84e2b550>}

**Comment by teek541** [comment]
FYI, I got it working, I'll post my configuration later.  I had to set some optional parameters.

**Comment by teek541** [comment]
For anyone finding this thread later, the following is my apps.yaml configuration for the qolsys_panel

qolsys_panel:
  module: gateway
  class: QolsysGateway
  panel_host: 192.168.20.223
  panel_mac: 3c:31:78:b8:6c:e1
  panel_token: !secret panel_token
  panel_user_code: !secret panel_user_code
  mqtt_namespace: mqtt
  request_topic: qolsys/requests # Optional
  qolsys_info_topic: qolsys/panel/info # Optional
  qolsys_zone_update_topic: qolsys/panel/zone_update # Optional
  qolsys_zone_event_topic: qolsys/panel/zone_event # Optional
  qolsys_alarming_event_topic: qolsys/panel/alarming # Optional
  qolsys_disarming_event_topic: qolsys/panel/disarm # Optional
  qolsys_confirm_arm_code: False # Optional
  qolsys_confirm_disarm_code: False # Optional
  qolsys_arm_away_always_instant: False # Optional
  discovery_topic: homeassistant
  log_level: DEBUG
  
  It's also worth noting that in your secrets.yaml file, you need to put your disarm code in quotes. "[code]"  Doing this sets the default user code used when clicking on your entity and clicking "disarm".

**Comment by teek541** [comment]
For anyone finding this thread later, the following is my apps.yaml configuration for the qolsys_panel

qolsys_panel:
module: gateway
class: QolsysGateway
panel_host: 192.168.XX.XXX
panel_mac: 3c:31:78:b8:XX:XX
panel_token: !secret panel_token
panel_user_code: !secret panel_user_code
mqtt_namespace: mqtt
request_topic: qolsys/requests # Optional
qolsys_info_topic: qolsys/panel/info # Optional
qolsys_zone_update_topic: qolsys/panel/zone_update # Optional
qolsys_zone_event_topic: qolsys/panel/zone_event # Optional
qolsys_alarming_event_topic: qolsys/panel/alarming # Optional
qolsys_disarming_event_topic: qolsys/panel/disarm # Optional
qolsys_confirm_arm_code: False # Optional
qolsys_confirm_disarm_code: False # Optional
qolsys_arm_away_always_instant: False # Optional
discovery_topic: homeassistant
log_level: DEBUG

It's also worth noting that in your secrets.yaml file, you need to put your disarm code in quotes. "[code]" Doing this sets the default user code used when clicking on your entity and clicking "disarm".

**Comment by XaF** [comment]
Hello!

Sorry I didn't get to your thread earlier! Awesome that you figured out the issue, and thanks a lot for sharing back your solution!

The panel code quotes made me realize that I could add a warning message in the logs if the code is loaded as integer vs. string, as it would at least give a hint of what is happening (if a code starts with 0 and is specified without quotes, the 0 will disappear).
