### ISSUE TITLE
Guide has missing steps about MQTT Config needed in apps.yaml

### ISSUE THREAD

**Issue by alfredopisano** [XaF/qolsysgw#128]
I'm Getting this error when i try to start the app: 

`2023-10-09 09:57:01.177800 WARNING qolsys_panel: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 160, in initialize_app
    await init()
  File "/config/appdaemon/apps/qolsysgw/gateway.py", line 79, in initialize
    raise MqttPluginUnavailableException(
mqtt.exceptions.MqttPluginUnavailableException: Unable to load the MQTT Plugin from AppDaemon, have you configured the MQTT plugin properly in appdaemon.yaml?

2023-10-09 09:57:01.177867 WARNING qolsys_panel: ------------------------------------------------------------`

I Tried adding a conifg to apps.yaml but its not working. Does anyone have any information on what is needed in apps.yaml to get QolsysGateway to work?

**Comment by alfredopisano** [comment]
Incase anyone else stumbles upon this i had to add this code block to the appdaemon.yaml file:

MQTT:
      type: mqtt
      namespace: mqtt # needed
      verbose: True
      client_host: mqtt://192.168.1.101
      client_port: 1883
      client_id: hass-mqtt

**Comment by alfredopisano** [comment]
There is steps in there i missed them closing issue
