### ISSUE TITLE
App Daemon update from 0.14 to 0.15 - need change in installation instructions

### ISSUE THREAD

**Issue by amogh79** [XaF/qolsysgw#132]
Hi,

Please find attached the screenshot for the update of AppDaemon and the folder structure is changing. Please update the instructions to reflect these changes.

Thanks
Amogh
![AppDaemonUpdate](https://github.com/XaF/qolsysgw/assets/12402030/1ed7868c-952f-469f-bb6d-fd68f62bc8e7)

**Comment by XaF** [comment]
This only applies to people using the AppDaemon add-on and HASSOS if I'm not mistaken?
In which case, this shouldn't require any update of documentation for `qolsysgw` since its documentation only has a link for the add-on setup, not a full guide!

**Comment by amogh79** [comment]
@XaF there are instructions which specify settings in appdaemon.yml and apps.yml. Now these files are moved to addon_configs/xyz_appdaemon

**Comment by XaF** [comment]
Which part of the documentation are you referring too?
The main documentation has been written with docker setup in mind (not HASSOS and addons), but should work for both. I can add a callout if there's a place that specifies paths, but I do not have / use the addons approach so won't be able to write something accurate. I'm open to a pull request to update the documentation though!

**Comment by Tobbe7612** [comment]
I have the same thing and using HASSOS. The QolsysGW-app is installed in a directory that AppDaemon does not use after the update. I managed to find that it was possible to point out to appdaemon where the apps are installed by adding "app_dir" configuration in the appdaemon.yaml file.
Can this be a solution or?
Not an expert in this topics I'm afraid.

**Comment by XaF** [comment]
> The QolsysGW-app is installed in a directory that AppDaemon does not use after the update

That is surprising - could that be a HACS configuration change?
I could add a disclaimer for installation location for manual installs, but that won't help for installations done through HACS (which is the preferred way) if it's not doing the right thing when using addons

**Comment by Tobbe7612** [comment]
Don't you think it might be possible to just point the AppDamon application to the correct path?

**Comment by XaF** [comment]
You're right! Following your previous comment mentioning `app_dir`, seems that it would be the approach to take. I was able to find this other comment that suggests the same approach: https://github.com/hassio-addons/addon-appdaemon/issues/302#issuecomment-1816194738

So I guess the simplest solution to this is to add in AppDaemon configuration the `app_dir` parameter to tell it to behave as it always behaved before that latest update 😅 

Will have to think about how to convey that in the documentation since I mostly wrote it with a docker manual setup in mind, while using that or HASSOS was pretty much the same idea.

**Comment by Tobbe7612** [comment]
Thanks, I will try this tomorrow

**Comment by Tobbe7612** [comment]
It didn't work for me. Got some Mqtt issues. Might be a local problem for me but it seems like there is a complain about bad protocol in the logs

**Comment by XaF** [comment]
Are you talking about AppDaemon logs ? Home Assistant logs ? MQTT logs ?

**Comment by Tobbe7612** [comment]
Get this in the AppDaemon log:
Can you help me?

gaierror: [Errno -2] Name does not resolve
2024-01-17 19:45:25.837347 INFO qolsys_panel: sleeping 60 second(s) before reconnecting
2024-01-17 19:46:25.842151 INFO qolsys_panel: Establishing connection to http://192.168.68.51:12345
2024-01-17 19:46:25.846147 ERROR qolsys_panel: error while listening
Traceback (most recent call last):
  File "/config/apps/qolsysgw/qolsys/socket.py", line 72, in listen
    reader, writer = await asyncio.open_connection(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/asyncio/base_events.py", line 1045, in create_connection
    infos = await self._ensure_resolved(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/asyncio/base_events.py", line 1419, in _ensure_resolved
    return await loop.getaddrinfo(host, port, family=family, type=type,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/asyncio/base_events.py", line 867, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gaierror: [Errno -2] Name does not resolve
2024-01-17 19:46:25.849763 INFO qolsys_panel: sleeping 60 second(s) before reconnecting

**Comment by Tobbe7612** [comment]
Do you see anything strange in the log I posted earlier? Sorry for asking again

**Comment by Tobbe7612** [comment]
Solved it! Stupid error from my side. Sorry
