### ISSUE TITLE
Arming IQ Pro to Night throws an error

### ISSUE THREAD

**Issue by alistairg** [XaF/qolsysgw#160]
### Before submitting this form

- [X] I have checked that there hasn't been a similar issue submitted in the past

- [X] I have updated the issue title to something relevant and clear to understand the bug I'm facing

### Description of the bug

When arming to night an error is raised. Checking in the code it looks like support for ARM_NIGHT has been commented out - before I start to attack this, I wanted to see if this was because of some other issue, or simply not yet implemented?

### Expected behavior

Home assistant status should reflect the ```armed_night``` nature of the panel

### DEBUG logs

Traceback (most recent call last):
  File "/config/apps/qolsysgw/mqtt/listener.py", line 47, in event_callback
    await self._callback(event)

  File "/config/apps/qolsysgw/gateway.py", line 210, in mqtt_event_callback
    self._state.update(event)

  File "/config/apps/qolsysgw/qolsys/state.py", line 56, in update
    self.notify(change=self.NOTIFY_UPDATE_PARTITIONS,

  File "/config/apps/qolsysgw/qolsys/observable.py", line 23, in notify
    callback(self, **payload)

  File "/config/apps/qolsysgw/mqtt/updater.py", line 57, in _state_update
    self._factory.wrap(partition).configure()

  File "/config/apps/qolsysgw/mqtt/updater.py", line 218, in configure
    self.update_state()

  File "/config/apps/qolsysgw/mqtt/updater.py", line 426, in update_state
    payload=self.ha_status,
            ^^^^^^^^^^^^^^

  File "/config/apps/qolsysgw/mqtt/updater.py", line 342, in ha_status
    raise ValueError('We need to put a better error here, but '
ValueError: We need to put a better error here, but we found an unsupported status: 'ARM_NIGHT'

**Comment by XaF** [comment]
> When arming to night an error is raised. Checking in the code it looks like support for ARM_NIGHT has been commented out - before I start to attack this, I wanted to see if this was because of some other issue, or simply not yet implemented?

The main issue is not being able to identify which panel is what, and so which real set of features are available. To my knowledge, no panel API allows to know the current panel version, and this was built around an IQ Panel 2+ initially. If the IQ Pro supports night, support should be able to be added. Ideally, we'll want to add some configuration option around if arm night should be available or not.

**Comment by Brandonlive2000** [comment]
The IQ Panel 4 has a night arm mode. 

I was able to edit the qolsysgw files to include night arming code, and I now can accurately see status when system is armed in night mode. But the command does not work - ie nothing happens when I try to activate night mode using the HA plugin. I’m not savvy with this stuff but it looks like the “ARM_NIGHT” command is being sent but perhaps it is not recognized by the panel. 

I’d be very interested in being able to ARM_NIGHT if anyone can figure it out. 

Xaf, I do think the code could be modified so that the default install will recognize the status of night armed when it is sent out by the panel. Having that won’t create any issues for people who don’t have night mode since the panel will never give out that status.

**Comment by EHylands** [comment]
Need to add following partition status: `ARM_NIGHT` and  `ARM-NIGHT-EXIT-DELAY`

My panel  won't accept C4 `ARM_NIGHT` or `ARM-NIGHT`  command though ... (I don't have any night mode sensors configured)

```
{
"version":1,
"source":"C4",
"action":"ARMING",
"nonce":"",
"token":"[***]",
"usercode":"[***]",
"partition_id":0,
"arming_type":"ARM_NIGHT",
"delay":0,
"bypass":"false"
}
```

Following command works on local MQTT server:
```
{
"eventName": "ipcCall", 
"ipcServiceName": "qinternalservice", 
"ipcInterfaceName": "android.os.IQInternalService", 
"ipcTransactionID": 7, 
"ipcRequest": [{"dataType": "string", "dataValue": "{"operation_name": "ui_armnight", "bypass_zoneid_set": "[]", "userID": 0, "partitionID": 0, "exitSoundValue": "OFF", "entryDelayValue": "OFF", "multiplePartitionsSelected": false, "instant_arming": true, "final_exit_arming_selected": false, "manually_selected_zones": "[]", "operation_source": 1, "macAddress": "*"}"}], 
"requestID": "994a837c-2d51-4b8f-9659-30056fed1f42", 
"responseTopic": "response_*", 
"remoteMacAddress": "*"
}
```
