### ISSUE TITLE
WARNING MQTT: Code: 400, error: 400: Bad Request

### ISSUE THREAD

**Issue by continuousmining** [XaF/qolsysgw#162]
### Before submitting this form

- [X] I have checked that there hasn't been a similar issue submitted in the past

- [X] I have updated the issue title to something relevant and clear to understand the bug I'm facing

### Description of the bug

Not connecting to MTQ Broker, giving the below errors in the appdeamon logs. 

ARNING MQTT: Error calling Home Assistant service mqtt/mqtt/publish
WARNING MQTT: Code: 400, error: 400: Bad Request

### Expected behavior

No errors

### DEBUG logs

uture: <Task finished name='Task-308' coro=<ADAPI.call_service() done, defined at /usr/lib/python3.11/site-packages/appdaemon/adapi.py:1691> exception=ServiceException('Unknown service (mqtt/mqtt/subscribe) in call_service from qolsys_panel')>
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/adapi.py", line 1762, in call_service
    return await self.AD.services.call_service(namespace, d, s, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/appdaemon/services.py", line 169, in call_service
    raise ServiceException(f"Unknown service ({namespace}/{domain}/{service}) in call_service from {name}")
ServiceException: Unknown service (mqtt/mqtt/subscribe) in call_service from qolsys_panel
2024-09-08 21:21:58.317521 DEBUG qolsys_panel: Calling listen_event for qolsys_panel
2024-09-08 21:21:58.342416 INFO qolsys_panel: Establishing connection to 192.168.1.231:12345
2024-09-08 21:21:58.500199 DEBUG qolsys_panel: Sending: {"nonce": "qolsys", "source": "C4", "version": 0, "action": "INFO", "info_type": "SUMMARY", "token": "jvjwx7"}
2024-09-08 21:21:58.502283 DEBUG qolsys_panel: Qolsys callback for connection event
2024-09-08 21:21:58.503000 DEBUG qolsys_panel: call_service: mqtt/publish, {'namespace': 'mqtt', 'retain': True, 'topic': 'homeassistant/sensor/qolsys_panel_last_error/config', 'payload': '{"name": "Last Error", "device_class": "timestamp", "state_topic": "homeassistant/sensor/qolsys_panel_last_error/state", "availability_mode": "all", "availability": [{"topic": "homeassistant/alarm_control_panel/qolsys_panel/availability", "payload_available": "online", "payload_not_available": "offline"}, {"topic": null, "payload_available": null, "payload_not_available": null}], "json_attributes_topic": "homeassistant/sensor/qolsys_panel_last_error/attributes", "unique_id": "qolsys_panel_last_error", "device": {"name": "Qolsys Panel", "identifiers": ["qolsys_panel"], "manufacturer": "Qolsys", "model": "IQ Panel 2+"}}'}
2024-09-08 21:21:58.503379 DEBUG qolsys_panel: call_service: mqtt/publish, {'namespace': 'mqtt', 'retain': True, 'topic': 'homeassistant/alarm_control_panel/qolsys_panel/availability', 'payload': 'online'}
2024-09-08 21:21:58.503458 DEBUG qolsys_panel: call_service: mqtt/publish, {'namespace': 'mqtt', 'retain': True, 'topic': 'homeassistant/sensor/qolsys_panel_last_error/state', 'payload': None}
2024-09-08 21:21:58.503553 DEBUG qolsys_panel: call_service: mqtt/publish, {'namespace': 'mqtt', 'retain': True, 'topic': 'homeassistant/sensor/qolsys_panel_last_error/attributes', 'payload': '{"type": null, "desc": null}'}
2024-09-08 21:21:58.509239 DEBUG qolsys_panel: Data received (len: 3): ACK
2024-09-08 21:21:58.511624 DEBUG qolsys_panel: ACK - ignoring.
2024-09-08 21:21:58.532561 WARNING MQTT: Error calling Home Assistant service mqtt/mqtt/publish
2024-09-08 21:21:58.548422 DEBUG qolsys_panel: Encoding detection: ascii is most likely the one.
2024-09-08 21:21:58.548637 WARNING MQTT: Code: 400, error: 400: Bad Request
2024-09-08 21:21:58.580488 INFO qolsys_panel: Previous message repeated 1 times
2024-09-08 21:21:58.582243 DEBUG qolsys_panel: Data received (len: 7440): {"event":"INFO","info_type":"SUMMARY","partition_list":

### Additional context

My yaml files include the login to the MQTT broker the name space, all the defaults, tried with and without, nothing works.

**Comment by continuousmining** [comment]
Logger: homeassistant.components.mqtt.mixins
Source: components/mqtt/mixins.py:166
integration: MQTT ([documentation](https://www.home-assistant.io/integrations/mqtt), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+mqtt%22))
First occurred: September 7, 2024 at 9:22:47 PM (13 occurrences)
Last logged: 9:33:17 PM

Error 'string value is None for dictionary value @ data['availability'][1]['topic']' when processing MQTT discovery message topic: 'homeassistant/sensor/qolsys_panel_last_error/config', message: '{'device_class': 'timestamp', 'state_topic': 'homeassistant/sensor/qolsys_panel_last_error/state', 'availability_mode': 'all', 'availability': [{'topic': 'homeassistant/alarm_control_panel/qolsys_panel/availability', 'payload_available': 'online', 'payload_not_available': 'offline'}, {'topic': None, 'payload_available': None, 'payload_not_available': None}], 'json_attributes_topic': 'homeassistant/sensor/qolsys_panel_last_error/attributes', 'unique_id': 'qolsys_panel_last_error', 'device': {'identifiers': ['qolsys_panel'], 'manufacturer': 'Qolsys', 'model': 'IQ Panel 2+', 'name': 'Qolsys Panel'}, 'name': 'Last Error', 'platform': 'mqtt'}'

**Comment by continuousmining** [comment]
fixed it. poor instrucitons.
