### ISSUE TITLE
Integration's socket doesn't reconnect upon [some?] failures

### ISSUE THREAD

**Issue by kevin-david** [XaF/qolsysgw#2]
When I changed some wifi settings earlier, the sensors became `Unavailable` and never came back. Restarting AppDaemon fixed this, but it seems like a good idea to be resilient to transient network issues inside the integration itself

```
2022-01-01 00:28:38.165051 DEBUG qolsys_panel: Sending keep-alive
2022-01-01 00:28:38.303066 ERROR qolsys_panel: error while listening
Traceback (most recent call last):
  File "/config/appdaemon/apps/qolsysgw/qolsys/socket.py", line 81, in listen
    line = await reader.readline()
  File "/usr/lib/python3.9/asyncio/streams.py", line 540, in readline
    line = await self.readuntil(sep)
  File "/usr/lib/python3.9/asyncio/streams.py", line 632, in readuntil
    await self._wait_for_data('readuntil')
  File "/usr/lib/python3.9/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 856, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer
2022-01-01 00:28:38.308925 DEBUG qolsys_panel: Qolsys callback for disconnection event
2022-01-01 00:28:38.311177 DEBUG qolsys_panel: call_service: mqtt/publish, {'namespace': 'mqtt', 'retain': True, 'topic': 'homeassistant/alarm_control_panel/qolsys_panel/availability', 'payload': 'offline'}
2022-01-01 00:28:38.316187 ERROR qolsys_panel: Task exception was never retrieved
future: <Task finished name='Task-335' coro=<QolsysSocket.listen() done, defined at /config/appdaemon/apps/qolsysgw/qolsys/socket.py:59> exception=ConnectionResetError(104, 'Connection reset by peer')>
Traceback (most recent call last):
  File "/config/appdaemon/apps/qolsysgw/qolsys/socket.py", line 121, in listen
    await writer.wait_closed()
  File "/usr/lib/python3.9/asyncio/streams.py", line 359, in wait_closed
    await self._protocol._get_close_waiter(self)
  File "/config/appdaemon/apps/qolsysgw/qolsys/socket.py", line 81, in listen
    line = await reader.readline()
  File "/usr/lib/python3.9/asyncio/streams.py", line 540, in readline
    line = await self.readuntil(sep)
  File "/usr/lib/python3.9/asyncio/streams.py", line 632, in readuntil
    await self._wait_for_data('readuntil')
  File "/usr/lib/python3.9/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 856, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by XaF** [comment]
If you can reproduce the error, please try again [with the `dev` branch](https://github.com/XaF/qolsysgw/tree/dev), as I just pushed a small fix that should resolve that issue! :)

**Comment by kevin-david** [comment]
I know it's probably not the same - but I attempted to repro this with your changes by blocking the panel from connecting to wifi for a while and eventually allowing it back in. When it was allowed back in and rebooted, it reconnected automatically l. So that was good!

**Comment by XaF** [comment]
I'll consider it's good enough a test :)
I merged this to the main branch too! Thanks again!
