### ISSUE TITLE
Namespace error

### ISSUE THREAD

**Issue by robgarrett** [XaF/qolsysgw#28]
NamespaceException: (‘Unknown namespace (%s) in call_service from %s’, ‘mqtt’, ‘qolsys_panel’)

HA on RPi4
Qolsys Panel 2+ 4.2.0
Control4 and remote access granted
Updated app.yaml with IP
Mosquito MQTT broker installed with HACS

**Comment by robgarrett** [comment]
More details...

Seems that the gateway is not getting anything from my panel.

 ERROR qolsys_panel: Task exception was never retrieved future: <Task finished name='Task-361' coro=<QolsysSocket.listen() done, defined at /config/appdaemon/apps/qolsysgw/qolsys/socket.py:60> exception=AttributeError("'NoneType' object has no attribute 'get'")> Traceback (most recent call last): File "/config/appdaemon/apps/qolsysgw/qolsys/socket.py", line 119, in listen await self._disconnected_callback() File "/config/appdaemon/apps/qolsysgw/gateway.py", line 158, in qolsys_disconnected_callback self._factory.wrap(self._state).set_unavailable() File "/config/appdaemon/apps/qolsysgw/mqtt/updater.py", line 500, in wrap return klass(obj, *self._args, **self._kwargs) File "/config/appdaemon/apps/qolsysgw/mqtt/updater.py", line 205, in __init__ super().__init__(*args, **kwargs) File "/config/appdaemon/apps/qolsysgw/mqtt/updater.py", line 86, in __init__ self._birth_topic = mqtt_plugin_cfg.get('birth_topic') AttributeError: 'NoneType' object has no attribute 'get'

**Comment by robgarrett** [comment]
Finally, figured out the issue: my appdaemon wasn't configured correctly.
As a new user of HASS, there's a lot of assumption in the setup of the qolsysgw that assumes you have the appdaemon running and MQTT configured correctly. Maybe a check list in the documentation: "did you check....?" would be useful.

**Comment by robgarrett** [comment]
Closing, now working.
