### ISSUE TITLE
Qolsysgw app state remains ‘idle’ 

### ISSUE THREAD

**Issue by epther** [XaF/qolsysgw#29]
I’m running into difficulties after completing the setup steps in the README, the Qolsys Gateway app in AppDaemon appears to remain ‘idle’ and I do not see any new sensors added in hassio integrations.

AppDaemon logs appear to show an error after initialization (“Error setting state unavailable”, and “Task exeption was never retrieved”). Any ideas what may be causing this? Is this related to my faulty configuration?

Thank you in advance - I’m relatively new to HA, apologies in advance for ignorant questions.

```
2022-10-12 23:04:03.919174 INFO AppDaemon: Initializing app qolsys_panel using class QolsysGateway from module gateway
2022-10-12 23:04:04.124150 INFO qolsys_panel: Starting
2022-10-12 23:04:04.131690 ERROR qolsys_panel: Error setting state unavailable; pursuing
Traceback (most recent call last):
  File "/config/appdaemon/apps/qolsysgw/gateway.py", line 87, in initialize
    self._factory.wrap(self._state).set_unavailable()
  File "/config/appdaemon/apps/qolsysgw/mqtt/updater.py", line 500, in wrap
    return klass(obj, *self._args, **self._kwargs)
  File "/config/appdaemon/apps/qolsysgw/mqtt/updater.py", line 205, in __init__
    super().__init__(*args, **kwargs)
  File "/config/appdaemon/apps/qolsysgw/mqtt/updater.py", line 86, in __init__
    self._birth_topic = mqtt_plugin_cfg.get('birth_topic')
AttributeError: 'NoneType' object has no attribute 'get'
2022-10-12 23:04:04.151068 INFO qolsys_panel: Started
2022-10-12 23:04:04.153577 INFO AppDaemon: App initialization complete
2022-10-12 23:04:04.162270 ERROR qolsys_panel: Task exception was never retrieved
future: <Task finished name='Task-196' coro=<ADAPI.call_service() done, defined at /usr/lib/python3.10/site-packages/appdaemon/adapi.py:1677> exception=NamespaceException('Unknown namespace (%s) in call_service from %s', 'mqtt', 'qolsys_panel')>
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/adapi.py", line 1748, in call_service
    return await self.AD.services.call_service(namespace, d, s, kwargs)
  File "/usr/lib/python3.10/site-packages/appdaemon/services.py", line 152, in call_service
    raise NamespaceException("Unknown namespace (%s) in call_service from %s", namespace, name)
NamespaceException: ('Unknown namespace (%s) in call_service from %s', 'mqtt', 'qolsys_panel')
2022-10-12 23:04:04.168274 ERROR qolsys_panel: Task exception was never retrieved
future: <Task finished name='Task-198' coro=<ADAPI.call_service() done, defined at /usr/lib/python3.10/site-packages/appdaemon/adapi.py:1677> exception=NamespaceException('Unknown namespace (%s) in call_service from %s', 'mqtt', 'qolsys_panel')>
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/adapi.py", line 1748, in call_service
    return await self.AD.services.call_service(namespace, d, s, kwargs)
  File "/usr/lib/python3.10/site-packages/appdaemon/services.py", line 152, in call_service
    raise NamespaceException("Unknown namespace (%s) in call_service from %s", namespace, name)
NamespaceException: ('Unknown namespace (%s) in call_service from %s', 'mqtt', 'qolsys_panel')
2022-10-12 23:04:04.182905 INFO qolsys_panel: Establishing connection to 192.168.100.126:12345
2022-10-12 23:06:13.810968 ERROR qolsys_panel: error while listening
Traceback (most recent call last):
  File "/config/appdaemon/apps/qolsysgw/qolsys/socket.py", line 73, in listen
    reader, writer = await asyncio.open_connection(
  File "/usr/lib/python3.10/asyncio/streams.py", line 47, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('192.168.100.126', 12345)
2022-10-12 23:06:13.821914 ERROR qolsys_panel: Task exception was never retrieved
future: <Task finished name='Task-237' coro=<QolsysSocket.listen() done, defined at /config/appdaemon/apps/qolsysgw/qolsys/socket.py:60> exception=AttributeError("'NoneType' object has no attribute 'get'")>
Traceback (most recent call last):
  File "/config/appdaemon/apps/qolsysgw/qolsys/socket.py", line 119, in listen
    await self._disconnected_callback()
  File "/config/appdaemon/apps/qolsysgw/gateway.py", line 158, in qolsys_disconnected_callback
    self._factory.wrap(self._state).set_unavailable()
  File "/config/appdaemon/apps/qolsysgw/mqtt/updater.py", line 500, in wrap
    return klass(obj, *self._args, **self._kwargs)
  File "/config/appdaemon/apps/qolsysgw/mqtt/updater.py", line 205, in __init__
    super().__init__(*args, **kwargs)
  File "/config/appdaemon/apps/qolsysgw/mqtt/updater.py", line 86, in __init__
    self._birth_topic = mqtt_plugin_cfg.get('birth_topic')
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by XaF** [comment]
This looks like the same issue as discussed in #31 (i.e. the MQTT plugin is not properly configured)
Closing as duplicate.
