### ISSUE TITLE
Cant get it working at all - MQTT badly configured in AppDaemon

### ISSUE THREAD

**Issue by Kapncanada** [XaF/qolsysgw#31]
Hello, Ive followed the instructions multiple times and I cannot get this working at all. Im at a loss and the App Deamon log is spitting out a lot of errors. Is there a way you could point me in the right direction?

Thanks

```
2022-10-31 01:09:20.340820 INFO HASS: All startup conditions met
2022-10-31 01:09:20.348293 INFO AppDaemon: Got initial state from namespace default
2022-10-31 01:09:22.325636 INFO AppDaemon: Scheduler running in realtime
2022-10-31 01:09:22.333538 INFO AppDaemon: Adding /config/appdaemon/apps to module import path
2022-10-31 01:09:22.335468 INFO AppDaemon: Adding /config/appdaemon/apps/qolsysgw to module import path
2022-10-31 01:09:22.337120 INFO AppDaemon: Adding /config/appdaemon/apps/qolsysgw/mqtt to module import path
2022-10-31 01:09:22.338803 INFO AppDaemon: Adding /config/appdaemon/apps/qolsysgw/qolsys to module import path
2022-10-31 01:09:22.374638 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/hello.py
2022-10-31 01:09:22.394899 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/qolsysgw/gateway.py
2022-10-31 01:09:22.400791 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/mqtt/updater.py - ignoring
2022-10-31 01:09:22.401284 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/mqtt/utils.py - ignoring
2022-10-31 01:09:22.401752 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/mqtt/exceptions.py - ignoring
2022-10-31 01:09:22.402197 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/mqtt/listener.py - ignoring
2022-10-31 01:09:22.402655 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/state.py - ignoring
2022-10-31 01:09:22.403106 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/events.py - ignoring
2022-10-31 01:09:22.403573 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/control.py - ignoring
2022-10-31 01:09:22.404019 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/sensors.py - ignoring
2022-10-31 01:09:22.404509 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/partition.py - ignoring
2022-10-31 01:09:22.404959 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/config.py - ignoring
2022-10-31 01:09:22.405430 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/actions.py - ignoring
2022-10-31 01:09:22.405884 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/utils.py - ignoring
2022-10-31 01:09:22.406347 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/observable.py - ignoring
2022-10-31 01:09:22.406820 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/socket.py - ignoring
2022-10-31 01:09:22.407296 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/qolsysgw/qolsys/exceptions.py - ignoring
2022-10-31 01:09:22.407718 INFO AppDaemon: Initializing app hello_world using class HelloWorld from module hello
2022-10-31 01:09:22.408501 INFO AppDaemon: Initializing app qolsys_panel using class QolsysGateway from module gateway
2022-10-31 01:09:22.439640 INFO hello_world: Hello from AppDaemon
2022-10-31 01:09:22.440292 INFO hello_world: You are now ready to run Apps!
2022-10-31 01:09:22.443932 INFO qolsys_panel: Starting
2022-10-31 01:09:22.446193 ERROR qolsys_panel: Error setting state unavailable; pursuing
Traceback (most recent call last):
  File "/config/appdaemon/apps/qolsysgw/gateway.py", line 87, in initialize
    self._factory.wrap(self._state).set_unavailable()
  File "/config/appdaemon/apps/qolsysgw/mqtt/updater.py", line 500, in wrap
    return klass(obj, *self._args, **self._kwargs)
  File "/config/appdaemon/apps/qolsysgw/mqtt/updater.py", line 205, in __init__
    super().__init__(*args, **kwargs)
  File "/config/appdaemon/apps/qolsysgw/mqtt/updater.py", line 86, in __init__
    self._birth_topic = mqtt_plugin_cfg.get('birth_topic')
AttributeError: 'NoneType' object has no attribute 'get'
2022-10-31 01:09:22.449464 INFO qolsys_panel: Started
2022-10-31 01:09:22.449948 INFO AppDaemon: App initialization complete
2022-10-31 01:09:22.451890 ERROR qolsys_panel: Task exception was never retrieved
future: <Task finished name='Task-223' coro=<ADAPI.call_service() done, defined at /usr/lib/python3.10/site-packages/appdaemon/adapi.py:1677> exception=NamespaceException('Unknown namespace (%s) in call_service from %s', 'mqtt', 'qolsys_panel')>
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/adapi.py", line 1748, in call_service
    return await self.AD.services.call_service(namespace, d, s, kwargs)
  File "/usr/lib/python3.10/site-packages/appdaemon/services.py", line 152, in call_service
    raise NamespaceException("Unknown namespace (%s) in call_service from %s", namespace, name)
NamespaceException: ('Unknown namespace (%s) in call_service from %s', 'mqtt', 'qolsys_panel')
2022-10-31 01:09:22.453249 ERROR qolsys_panel: Task exception was never retrieved
future: <Task finished name='Task-225' coro=<ADAPI.call_service() done, defined at /usr/lib/python3.10/site-packages/appdaemon/adapi.py:1677> exception=NamespaceException('Unknown namespace (%s) in call_service from %s', 'mqtt', 'qolsys_panel')>
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/adapi.py", line 1748, in call_service
    return await self.AD.services.call_service(namespace, d, s, kwargs)
  File "/usr/lib/python3.10/site-packages/appdaemon/services.py", line 152, in call_service
    raise NamespaceException("Unknown namespace (%s) in call_service from %s", namespace, name)
NamespaceException: ('Unknown namespace (%s) in call_service from %s', 'mqtt', 'qolsys_panel')
2022-10-31 01:09:22.456988 INFO qolsys_panel: Establishing connection to 192.168.2.21:12345
2022-10-31 01:09:22.859542 ERROR qolsys_panel: error while listening
Traceback (most recent call last):
  File "/config/appdaemon/apps/qolsysgw/qolsys/socket.py", line 78, in listen
    await self._connected_callback()
  File "/config/appdaemon/apps/qolsysgw/gateway.py", line 151, in qolsys_connected_callback
    self._factory.wrap(self._state).set_available()
  File "/config/appdaemon/apps/qolsysgw/mqtt/updater.py", line 500, in wrap
    return klass(obj, *self._args, **self._kwargs)
  File "/config/appdaemon/apps/qolsysgw/mqtt/updater.py", line 205, in __init__
    super().__init__(*args, **kwargs)
  File "/config/appdaemon/apps/qolsysgw/mqtt/updater.py", line 86, in __init__
    self._birth_topic = mqtt_plugin_cfg.get('birth_topic')
AttributeError: 'NoneType' object has no attribute 'get'
2022-10-31 01:09:22.876003 ERROR qolsys_panel: Task exception was never retrieved
future: <Task finished name='Task-263' coro=<QolsysSocket.listen() done, defined at /config/appdaemon/apps/qolsysgw/qolsys/socket.py:60> exception=AttributeError("'NoneType' object has no attribute 'get'")>
Traceback (most recent call last):
  File "/config/appdaemon/apps/qolsysgw/qolsys/socket.py", line 119, in listen
    await self._disconnected_callback()
  File "/config/appdaemon/apps/qolsysgw/gateway.py", line 158, in qolsys_disconnected_callback
    self._factory.wrap(self._state).set_unavailable()
  File "/config/appdaemon/apps/qolsysgw/mqtt/updater.py", line 500, in wrap
    return klass(obj, *self._args, **self._kwargs)
  File "/config/appdaemon/apps/qolsysgw/mqtt/updater.py", line 205, in __init__
    super().__init__(*args, **kwargs)
  File "/config/appdaemon/apps/qolsysgw/mqtt/updater.py", line 86, in __init__
    self._birth_topic = mqtt_plugin_cfg.get('birth_topic')
AttributeError: 'NoneType' object has no attribute 'get'
2022-10-31 01:09:24.330058 INFO AppDaemon: New client Admin Client connected
```

**Comment by maestreja** [comment]
im exactly on the same boat

**Comment by XaF** [comment]
Hey there!

Seems like you haven't followed the setup steps completely, as the MQTT module is not configured in AppDaemon according to the error message.

If you configure it, it should work!

**Comment by Kapncanada** [comment]
HI there, i've completed all the steps but I must be missing something with MQTT and the APP Deamon. I'm just not sure what the problem is. Ive defined the name space in both appdeamon and the app yaml files. Just not sure where to go from here. 

Thanks

**Comment by amogh79** [comment]
I am having same problem, unable to get working and getting same errors. Can you please let me know what I am missing from MQTT module installation. I installed Mosquitto MQTT broker using [ instructions here](https://github.com/home-assistant/addons/blob/master/mosquitto/DOCS.md).

**Comment by XaF** [comment]
This error message:

```

File "/config/appdaemon/apps/qolsysgw/mqtt/updater.py", line 86, in init
self._birth_topic = mqtt_plugin_cfg.get('birth_topic')
AttributeError: 'NoneType' object has no attribute 'get'
```

Tells me that the integration failed to load the MQTT plugin from appdaemon. This means you're most likely lacking:

```yaml
appdaemon:
 ...

  plugins:
    ...

    # And we need to add the MQTT plugin
    MQTT:
      type: mqtt
     ...
```

From the section https://github.com/XaF/qolsysgw#installing-appdaemon of the readme

**Comment by amogh79** [comment]
> 

This is how my apps.yaml configuration looks like

`
qolsys_panel:
  module: gateway
  class: QolsysGateway
  panel_host: 192.168.XX.108
  panel_token: xxxxxx
  panel_user_code: 9918XX
  arm_away_exit_delay: 60
  panel_device_name: IQ Panel 4
`

And this is what I have added in appdaemon.yml

`secrets: /config/secrets.yaml
appdaemon:
  latitude: 52.379189
  longitude: 4.899431
  elevation: 2
  time_zone: "America/Chicago"
  plugins:
    HASS:
      type: hass
  MQTT:
    type: mqtt
    namespace: gateway # We will need that same value in the apps.yaml configuration
    client_host: 192.168.50.239 # The IP address or hostname of the MQTT broker
    client_port: 1883 # The port of the MQTT broker, generally 1883
http:
  url: http://127.0.0.1:5050
admin:
api:`

I am not sure if the module and namespace means the same or its different and if that's causing the issues.

**Comment by XaF** [comment]
The section I quoted talks about the `appdaemon.yaml`, so not the same file!

**Comment by XaF** [comment]
It seems that your MQTT plugin is not picked up from the application. Double-check the indentation maybe? (I can't see the indentation from your pasting)

**Comment by XaF** [comment]
When I do edit your message, I can see that the `MQTT` section is badly indented! It should be aligned with `HASS` in the file.

**Comment by amogh79** [comment]
Thanks for pointing out the indentation error. Now I am getting this error, can you please help

2022-11-24 22:39:02.300746 CRITICAL MQTT: MQTT Client Disconnected Abruptly. Will attempt reconnection
2022-11-24 22:39:02.329167 CRITICAL MQTT: Could not complete MQTT Plugin initialization, trying again in 5 seconds
2022-11-24 22:39:10.308485 CRITICAL MQTT: Could not complete MQTT Plugin initialization, for Connection was refused due to Not Authorised

**Comment by chuckseguin** [comment]
I hope this topic gets noticed. I am in the same place is user amogh79: I get the exact same error message about MQTT refusing the connection.

Thanks in advance

**Comment by XaF** [comment]
```
Connection was refused due to Not Authorised
```

@amogh79 you seem to be using the wrong username/password to connect to your MQTT.

**Comment by Aipoc76** [comment]
the indention of MQTT must line up with HASS.  Heres mine, and it works flawlessly.  places with XXXX put your own stuff.

```
appdaemon:
  latitude: XXXX
  longitude: XXXXX
  elevation: XXXX
  time_zone: XXXX
  plugins:
    HASS:
      type: hass
    MQTT:
      type: mqtt
      namespace: mqtt
      client_host: core-mosquitto
      client_port: 1883
      client_user: mqttbroker # should be the user you have in your broker
      client_password: !secret mqtt_password # The password of the mqttbroker user
http:
  url: http://127.0.0.1:5050
  password: !secret ad_password # not needed but secures your mqtt web portal if you make one
  api_ssl_certificate: /ssl/fullchain.pem # only if you have security cert
  api_ssl_key: /ssl/privkey.pem # only if you have security key
admin:
api:
  ```
